/********************************************************************
* eventdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error eventdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableeventdict();
extern void G__cpp_setup_inheritanceeventdict();
extern void G__cpp_setup_typetableeventdict();
extern void G__cpp_setup_memvareventdict();
extern void G__cpp_setup_globaleventdict();
extern void G__cpp_setup_memfunceventdict();
extern void G__cpp_setup_funceventdict();
extern void G__set_cpp_environmenteventdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "myevent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__eventdictLN_TClass;
extern G__linked_taginfo G__eventdictLN_TBuffer;
extern G__linked_taginfo G__eventdictLN_TMemberInspector;
extern G__linked_taginfo G__eventdictLN_TObject;
extern G__linked_taginfo G__eventdictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__eventdictLN_string;
extern G__linked_taginfo G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__eventdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__eventdictLN_myVertex;
extern G__linked_taginfo G__eventdictLN_myTriggerObject;
extern G__linked_taginfo G__eventdictLN_myGenObject;
extern G__linked_taginfo G__eventdictLN_myMuon;
extern G__linked_taginfo G__eventdictLN_myElectron;
extern G__linked_taginfo G__eventdictLN_myTau;
extern G__linked_taginfo G__eventdictLN_myJet;
extern G__linked_taginfo G__eventdictLN_myMET;
extern G__linked_taginfo G__eventdictLN_mySV;
extern G__linked_taginfo G__eventdictLN_myevent;
extern G__linked_taginfo G__eventdictLN_vectorlEmyGenObjectcOallocatorlEmyGenObjectgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyGenObjectcOallocatorlEmyGenObjectgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyGenObjectcOallocatorlEmyGenObjectgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyTriggerObjectcOallocatorlEmyTriggerObjectgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyTriggerObjectcOallocatorlEmyTriggerObjectgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyTriggerObjectcOallocatorlEmyTriggerObjectgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyJetcOallocatorlEmyJetgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyJetcOallocatorlEmyJetgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyJetcOallocatorlEmyJetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyElectroncOallocatorlEmyElectrongRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyElectroncOallocatorlEmyElectrongRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyElectroncOallocatorlEmyElectrongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyMuoncOallocatorlEmyMuongRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyMuoncOallocatorlEmyMuongRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyMuoncOallocatorlEmyMuongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyTaucOallocatorlEmyTaugRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyTaucOallocatorlEmyTaugRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyTaucOallocatorlEmyTaugRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyMETcOallocatorlEmyMETgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyMETcOallocatorlEmyMETgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyMETcOallocatorlEmyMETgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyVertexcOallocatorlEmyVertexgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyVertexcOallocatorlEmyVertexgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyVertexcOallocatorlEmyVertexgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmySVcOallocatorlEmySVgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmySVcOallocatorlEmySVgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmySVcOallocatorlEmySVgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<myGenObject,allocator<myGenObject> > G__vectorlEmyGenObjectcOallocatorlEmyGenObjectgRsPgR;
typedef vector<myGenObject,allocator<myGenObject> >::iterator G__vectorlEmyGenObjectcOallocatorlEmyGenObjectgRsPgRcLcLiterator;
typedef vector<myTriggerObject,allocator<myTriggerObject> > G__vectorlEmyTriggerObjectcOallocatorlEmyTriggerObjectgRsPgR;
typedef vector<myTriggerObject,allocator<myTriggerObject> >::iterator G__vectorlEmyTriggerObjectcOallocatorlEmyTriggerObjectgRsPgRcLcLiterator;
typedef vector<myJet,allocator<myJet> > G__vectorlEmyJetcOallocatorlEmyJetgRsPgR;
typedef vector<myJet,allocator<myJet> >::iterator G__vectorlEmyJetcOallocatorlEmyJetgRsPgRcLcLiterator;
typedef vector<myElectron,allocator<myElectron> > G__vectorlEmyElectroncOallocatorlEmyElectrongRsPgR;
typedef vector<myElectron,allocator<myElectron> >::iterator G__vectorlEmyElectroncOallocatorlEmyElectrongRsPgRcLcLiterator;
typedef vector<myMuon,allocator<myMuon> > G__vectorlEmyMuoncOallocatorlEmyMuongRsPgR;
typedef vector<myMuon,allocator<myMuon> >::iterator G__vectorlEmyMuoncOallocatorlEmyMuongRsPgRcLcLiterator;
typedef vector<myTau,allocator<myTau> > G__vectorlEmyTaucOallocatorlEmyTaugRsPgR;
typedef vector<myTau,allocator<myTau> >::iterator G__vectorlEmyTaucOallocatorlEmyTaugRsPgRcLcLiterator;
typedef vector<myMET,allocator<myMET> > G__vectorlEmyMETcOallocatorlEmyMETgRsPgR;
typedef vector<myMET,allocator<myMET> >::iterator G__vectorlEmyMETcOallocatorlEmyMETgRsPgRcLcLiterator;
typedef vector<myVertex,allocator<myVertex> > G__vectorlEmyVertexcOallocatorlEmyVertexgRsPgR;
typedef vector<myVertex,allocator<myVertex> >::iterator G__vectorlEmyVertexcOallocatorlEmyVertexgRsPgRcLcLiterator;
typedef vector<mySV,allocator<mySV> > G__vectorlEmySVcOallocatorlEmySVgRsPgR;
typedef vector<mySV,allocator<mySV> >::iterator G__vectorlEmySVcOallocatorlEmySVgRsPgRcLcLiterator;
