./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_Tau__Run2017B-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_Tau__Run2017C-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_Tau__Run2017D-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_Tau__Run2017E-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_Tau__Run2017F-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleMuon__Run2017B-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleMuon__Run2017C-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleMuon__Run2017D-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleMuon__Run2017E-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleMuon__Run2017F-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleElectron__Run2017B-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleElectron__Run2017C-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleElectron__Run2017D-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleElectron__Run2017E-31Mar2018-v1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_data/1_SingleElectron__Run2017F-31Mar2018-v1.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ttbar_lep.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ttbar_had.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ttbar_semilep.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WJetsToLNu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WJetsToLNu_HT-70To100.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WJetsToLNu_HT-100To200.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WJetsToLNu_HT-200To400.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WJetsToLNu_HT-400To600.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WJetsToLNu_HT-600To800.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WJetsToLNu_HT-800To1200.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WJetsToLNu_HT-1200To2500.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WJetsToLNu_HT-2500ToInf.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-50.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DY1JetsToLL.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DY2JetsToLL.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DY3JetsToLL.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DY4JetsToLL.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYBBJetsToLL.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-50_HT-70to100.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-50_HT-100to200.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-50_HT-200to400.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-50_HT-400to600.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-50_HT-600to800.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-50_HT-800to1200.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-50_HT-1200to2500.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-50_HT-2500toInf.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/DYJetsToLL_M-10to50.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ZZTo4L.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ZZTo2L2Nu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ZZTo2L2Q.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ZZTo2Q2Nu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WZTo3LNu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WZTo1L1Nu2Q.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WZTo1L3Nu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WZTo2L2Q.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WWTo2L2Nu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WWToLNuQQ.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WWTo4Q.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ST_tW_antitop.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ST_tW_top.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ST_t-channel_antitop.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ST_t-channel_top.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/EWKWMinus2Jets_WToLNu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/EWKWPlus2Jets_WToLNu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/EWKZ2Jets_ZToLL.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ZH_HToBB_ZToLL.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ZH_HToBB_ZToQQ.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ZHToTauTau.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WplusHToTauTau.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WminusHToTauTau.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/VBFHToTauTau.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/GluGluHToTauTau.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ggZH_HToBB_ZToLL.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ggZH_HToTauTau_ZToQQ.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ZZZ.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WZZ.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WWW.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/WWZ.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ttHTobb.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ttHToNonbb.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/ttHToTauTau.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/TTWJetsToLNu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/TTWJetsToQQ.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/TTWW.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/TTWZ.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/TTWH.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/TTZH.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/TTZToLLNuNu.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/TTZToQQ.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_backgrounds/TTZZ.txt

./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_12.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_2.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_3.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_4.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_7.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_9.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_SM.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_cHHH5.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_cHHH2p45.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_cHHH1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/GluGluToHHTo2B2Tau_node_cHHH0.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/VBFHHTo2B2Tau_CV_1_5_C2V_1_C3_1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/VBFHHTo2B2Tau_CV_1_C2V_1_C3_0.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/VBFHHTo2B2Tau_CV_1_C2V_1_C3_1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/VBFHHTo2B2Tau_CV_1_C2V_1_C3_2.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/VBFHHTo2B2Tau_CV_1_C2V_2_C3_1.txt
./bin/getNumberEvents.exe /gwpool/users/dzuolo/HHbbtautatuAnalysisLegacy/CMSSW_10_2_16/src/KLUBAnalysis/inputFiles/Legacy2017_signals/ZZTo2B2Tau.txt
