source /opt/exp_soft/cms/t3/t3setup


#python scripts/skimNtuple.py -d True -k False -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsEEMuMu15Dic/SKIM_SingleMuon        -i inputFiles/miniAODv2_silverJson/SingleMuon_merged.txt
#python scripts/skimNtuple.py -d True -k False -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsEEMuMu15Dic/SKIM_Tau               -i inputFiles/miniAODv2_silverJson/Tau_merged.txt
#python scripts/skimNtuple.py -d True -k False -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsEEMuMu15Dic/SKIM_SingleElectron    -i inputFiles/miniAODv2_silverJson/SingleElectron_merged.txt


# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_TTJets          -i inputFiles/28Ago2015/5_TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1.txt              -x 831.76 
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_WJet            -i inputFiles/28Ago2015/1_WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1.txt          -x 61526.7 
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_DY              -i inputFiles/28Ago2015/2_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v3.txt     -x 6025.2 
# # python scripts/skimNtuple.py -s True -c  config/skim.cfg -n 50 -k False   -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_T-tchannel      -i inputFiles/28Ago2015/ MISSING    -x 70.69  
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_HHLambda20      -i inputFiles/28Ago2015/HH_Lambda20.txt                                                                       -x 3.605  
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_WW_TuneCUETP8M1 -i inputFiles/28Ago2015/6_WW_TuneCUETP8M1_13TeV-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1.txt     -x 63.21
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_WZ_TuneCUETP8M1 -i inputFiles/28Ago2015/7_WZ_TuneCUETP8M1_13TeV-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1.txt     -x 22.82
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_ZZ_TuneCUETP8M1 -i inputFiles/28Ago2015/8_ZZ_TuneCUETP8M1_13TeV-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v3.txt     -x 10.32
# # python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_TW-top          -i inputFiles/28Ago2015/     -x 71.2   
# # python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_TW-antitop      -i inputFiles/28Ago2015/     -x 71.2   

# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_DoubleEG_PromptReco        -i inputFiles/28Ago2015/10_DoubleEG__Run2015B-PromptReco-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_DoubleEG_17Jul2015         -i inputFiles/28Ago2015/9_DoubleEG__Run2015B-17Jul2015-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_SingleElectron_PromptReco  -i inputFiles/28Ago2015/6_SingleElectron__Run2015B-PromptReco-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_SingleElectron_17Jul2015   -i inputFiles/28Ago2015/7_SingleElectron__Run2015B-17Jul2015-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_SingleMuon_PromptReco      -i inputFiles/28Ago2015/1_SingleMuon__Run2015B-PromptReco-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_SingleMuon_17Jul2015       -i inputFiles/28Ago2015/2_SingleMuon__Run2015B-17Jul2015-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_Tau_PromptReco             -i inputFiles/28Ago2015/17_Tau__Run2015B-PromptReco-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_Tau_17Jul2015              -i inputFiles/28Ago2015/18_Tau__Run2015B-17Jul2015-v1.txt

# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_HHLambda1_New         -i inputFiles/13Ott2015//HH_Lambda1.txt       -x 0.0343
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_HHLambda20_New        -i inputFiles/13Ott2015//HH_Lambda20.txt      -x 3.602  
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_HHLambdam4_New        -i inputFiles/13Ott2015//HH_Lambdam4.txt      -x 0.411  
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims10_AllJets_NI/SKIM_HHLambda2dot46_New    -i inputFiles/13Ott2015//HH_Lambda2dot46.txt  -x 0.0144  

###### Run D data 25 ns --> un po' meno di 1.5/fb (da controllare vista la mancanza dei dati run C)
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_SingleMuon_31OttD_PromptReco        -i inputFiles/DataRunDTrigFix4Nov/5_SingleMuon__Run2015D-PromptReco-v4.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_Tau_31OttD_PromptReco               -i inputFiles/DataRunDTrigFix4Nov/4_Tau__Run2015D-PromptReco-v4.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_SingleElectron_31OttD_PromptReco    -i inputFiles/DataRunDTrigFix4Nov/6_SingleElectron__Run2015D-PromptReco-v4.txt

# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_SingleMuon_31OttD_05Oct2015        -i inputFiles/DataRunDTrigFix4Nov/2_SingleMuon__Run2015D-05Oct2015-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_Tau_31OttD_05Oct2015               -i inputFiles/DataRunDTrigFix4Nov/1_Tau__Run2015D-05Oct2015-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_SingleElectron_31OttD_05Oct2015    -i inputFiles/DataRunDTrigFix4Nov/3_SingleElectron__Run2015D-05Oct2015-v1.txt

# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_SingleMuon_14NovD_lumidiff_promptReco        -i inputFiles/Data14NovLumiDiff/2_SingleMuon__Run2015D-PromptReco-v4.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_Tau_14NovD_lumidiff_promptReco               -i inputFiles/Data14NovLumiDiff/1_Tau__Run2015D-PromptReco-v4.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_SingleElectron_14NovD_lumidiff_promptReco    -i inputFiles/Data14NovLumiDiff/3_SingleElectron__Run2015D-PromptReco-v4.txt


# # HH Signals
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims14_AllJets_NI_NoTrigger_2/SKIM_HHLambda1_New         -i inputFiles/28Ago2015/HH_Lambda1.txt       -x 0.00247
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims14_AllJets_NI_NoTrigger_2/SKIM_HHLambda20_New        -i inputFiles/28Ago2015/HH_Lambda20.txt      -x 0.259 
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims14_AllJets_NI_NoTrigger_2/SKIM_HHLambdam4_New        -i inputFiles/28Ago2015/HH_Lambdam4.txt      -x 0.0296  
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims14_AllJets_NI_NoTrigger_2/SKIM_HHLambda2dot46_New    -i inputFiles/28Ago2015/HH_Lambda2dot46.txt  -x 0.00104  

# # MC backgrounds
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims15_AllJets_NI_NoPURew/SKIM_WW_TuneCUETP8M1 -i inputFiles/28Ago2015/6_WW_TuneCUETP8M1_13TeV-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1.txt     -x 63.21
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims15_AllJets_NI_NoPURew/SKIM_WZ_TuneCUETP8M1 -i inputFiles/28Ago2015/7_WZ_TuneCUETP8M1_13TeV-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1.txt     -x 22.82
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims15_AllJets_NI_NoPURew/SKIM_ZZ_TuneCUETP8M1 -i inputFiles/28Ago2015/8_ZZ_TuneCUETP8M1_13TeV-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v3.txt     -x 10.32
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 60 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims15_AllJets_NI_NoPURew/SKIM_TTJets          -i inputFiles/28Ago2015/5_TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1.txt              -x 831.76 
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 60 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims15_AllJets_NI_NoPURew/SKIM_WJet            -i inputFiles/28Ago2015/1_WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1.txt          -x 61526.7 
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 60 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims15_AllJets_NI_NoPURew/SKIM_DY              -i inputFiles/28Ago2015/2_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v3.txt     -x 6025.2 


# TODO: single top, t-W, antit-W
# AND ZH
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims13_AllJets_NI/SKIM_ZH              -i inputFiles/28Ago2015/2_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8__RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v3.txt     -x 6025.2 


# ###### # MINIAODv2 bkgr samples - Silver JSON
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_WWToLNuQQ         -i inputFiles/miniAODv2_silverJson/27_WWToLNuQQ_13TeV-powheg__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 49.997
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_WWTo2L2Nu         -i inputFiles/miniAODv2_silverJson/28_WWTo2L2Nu_13TeV-powheg__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 12.178
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_WZTo2L2Q          -i inputFiles/miniAODv2_silverJson/29_WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 5.595
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_WZTo3LNu          -i inputFiles/miniAODv2_silverJson/30_WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 4.42965
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_WZTo1L3Nu         -i inputFiles/miniAODv2_silverJson/31_WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 3.05
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_WZTo1L1Nu2Q       -i inputFiles/miniAODv2_silverJson/32_WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 10.71
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_ZZTo2L2Nu      -i inputFiles/miniAODv2_silverJson/24_ZZTo2L2Nu_13TeV_powheg_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt   -x 0.564
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_ZZTo2L2Q       -i inputFiles/miniAODv2_silverJson/25_ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 3.22
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_ZZTo4L         -i inputFiles/miniAODv2_silverJson/26_ZZTo4L_13TeV-amcatnloFXFX-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 1.212
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_ST_tW_antitop_5f_inclusiveDecays   -i inputFiles/miniAODv2_silverJson/22_ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 35.6
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_ST_tW_top_5f_inclusiveDecays       -i inputFiles/miniAODv2_silverJson/23_ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt   -x 35.6
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_DYJetsToLL_M-50   -i inputFiles/miniAODv2_silverJson/4_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 6025.2
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_WJetsToLNu        -i inputFiles/miniAODv2_silverJson/3_WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 61526.7
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_TT_merged         -i inputFiles/miniAODv2_silverJson/TT_merged.txt   -x 831.76
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-250   -i inputFiles/miniAODv2_silverJson/5_GluGluToRadionToHHTo2B2Tau_M-250_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-300   -i inputFiles/miniAODv2_silverJson/9_GluGluToRadionToHHTo2B2Tau_M-300_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-350   -i inputFiles/miniAODv2_silverJson/12_GluGluToRadionToHHTo2B2Tau_M-350_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-400   -i inputFiles/miniAODv2_silverJson/13_GluGluToRadionToHHTo2B2Tau_M-400_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-450   -i inputFiles/miniAODv2_silverJson/14_GluGluToRadionToHHTo2B2Tau_M-450_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-500   -i inputFiles/miniAODv2_silverJson/15_GluGluToRadionToHHTo2B2Tau_M-500_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 100.0

# ### non resonant samples - SIlver JSON
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_HHLambda1         -i inputFiles/miniAODv2_silverJson/HH_Lambda1.txt        -x 0.00247
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_HHLambda20        -i inputFiles/miniAODv2_silverJson/HH_Lambda20.txt       -x 0.259 
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_HHLambdam4        -i inputFiles/miniAODv2_silverJson/HH_Lambdam4.txt       -x 0.0296  
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_HHLambda2dot46    -i inputFiles/miniAODv2_silverJson/HH_Lambda2p46.txt     -x 0.00104  

# #### DATA -- silver JSON
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_SingleMuon        -i inputFiles/miniAODv2_silverJson/SingleMuon_merged.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_Tau               -i inputFiles/miniAODv2_silverJson/Tau_merged.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims25_AllJets_NI/SKIM_SingleElectron    -i inputFiles/miniAODv2_silverJson/SingleElectron_merged.txt

#python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsMissingLumi_AllJets_NI/SKIM_SingleMuon_D_PromptReco   -i inputFiles/miniAODv2_silverJson/5_SingleMuon__Run2015D-PromptReco-v4.txt
#python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsMissingLumi_AllJets_NI/SKIM_SingleMuon_D_05Oct2015    -i inputFiles/miniAODv2_silverJson/2_SingleMuon__Run2015D-05Oct2015-v1.txt



# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_WJetsToLNu_HT-100To200             -i inputFiles/miniAODv2_silverJson/23_WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 1345.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_WJetsToLNu_HT-200To400             -i inputFiles/miniAODv2_silverJson/24_WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 359.7
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_WJetsToLNu_HT-400To600             -i inputFiles/miniAODv2_silverJson/25_WJetsToLNu_HT-400To600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 48.91
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_WJetsToLNu_HT-600ToInf             -i inputFiles/miniAODv2_silverJson/26_WJetsToLNu_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 18.77
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_DYJetsToLL_M-50_HT-100to200        -i inputFiles/miniAODv2_silverJson/28_DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 139.4
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_DYJetsToLL_M-50_HT-200to400        -i inputFiles/miniAODv2_silverJson/29_DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 42.75
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_DYJetsToLL_M-50_HT-400to600        -i inputFiles/miniAODv2_silverJson/30_DYJetsToLL_M-50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt   -x 5.497
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_DYJetsToLL_M-50_HT-600toInf        -i inputFiles/miniAODv2_silverJson/31_DYJetsToLL_M-50_HT-600toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 2.21

#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims18_AllJets_NI/SKIM_ST_tW_antitop_5f_inclusiveDecays   -i inputFiles/miniAODv2SVFit/ST_tW_antitop_5f_inclusiveDecays_HTauTau_25_11_15.txt   -x 35.6
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims18_AllJets_NI/SKIM_ST_tW_top_5f_inclusiveDecays       -i inputFiles/miniAODv2SVFit/ST_tW_top_5f_inclusiveDecays_HTauTau_25_11_15.txt   -x 35.6
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims18_AllJets_NI/SKIM_DYJetsToLL_M-50                    -i inputFiles/miniAODv2SVFit/DYJetsToLL_Inclusive_HTauTau_25_11_15.txt   -x 6025.2
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims18_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-300   -i inputFiles/miniAODv2SVFit/GluGluToRadionToHHTo2B2Tau_M-300_HTauTau_24_11_15.txt   -x 100.0
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims18_AllJets_NI/SKIM_WJetsToLNu                         -i inputFiles/miniAODv2SVFit/WJetsToLNu_Inclusive_HTauTau_25_11_15.txt   -x 61526.7
# TT: not yet merged!!
#python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 100 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsPROVVISORIE_AllJets_NI/SKIM_TT_merged                         -i inputFiles/miniAODv2SVFit/TT_merged_noSomeGen.txt   -x 831.76

# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_DYJetsToLL_M-50   -i inputFiles/miniAODv2VSfitForTalk/DYJetsToLL_Inclusive_HTauTau_26_11_15.txt   -x 6025.2
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 40 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_WJetsToLNu        -i inputFiles/miniAODv2VSfitForTalk/3_WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 61526.7
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_TT_merged                         -i inputFiles/miniAODv2VSfitForTalk/TT_merged.txt   -x 831.76
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-300   -i inputFiles/miniAODv2VSfitForTalk/GluGluToRadionToHHTo2B2Tau_M-300_HTauTau_26_11_15.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-250   -i inputFiles/miniAODv2VSfitForTalk/GluGluToRadionToHHTo2B2Tau_M-250_HTauTau_26_11_15.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-320   -i inputFiles/miniAODv2VSfitForTalk/GluGluToRadionToHHTo2B2Tau_M-320_HTauTau_26_11_15.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-500   -i inputFiles/miniAODv2VSfitForTalk/GluGluToRadionToHHTo2B2Tau_M-500_HTauTau_26_11_15.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-400   -i inputFiles/miniAODv2VSfitForTalk/GluGluToRadionToHHTo2B2Tau_M-400_HTauTau_26_11_15.txt   -x 100.0
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_ST_tW_antitop_5f_inclusiveDecays   -i inputFiles/miniAODv2VSfitForTalk/ST_tW_antitop_5f_inclusiveDecays_HTauTau_26_11_15.txt   -x 35.6
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_ST_tW_top_5f_inclusiveDecays       -i inputFiles/miniAODv2VSfitForTalk/ST_tW_top_5f_inclusiveDecays_HTauTau_26_11_15.txt   -x 35.6


# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_SingleMuon_31OttD_PromptReco        -i inputFiles/miniAODv2VSfitForTalk/5_SingleMuon__Run2015D-PromptReco-v4.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_Tau_31OttD_PromptReco               -i inputFiles/miniAODv2VSfitForTalk/4_Tau__Run2015D-PromptReco-v4.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_SingleElectron_31OttD_PromptReco    -i inputFiles/DataRunDTrigFix4Nov/6_SingleElectron__Run2015D-PromptReco-v4.txt

# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_SingleMuon_31OttD_05Oct2015        -i inputFiles/miniAODv2VSfitForTalk/2_SingleMuon__Run2015D-05Oct2015-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims20_Talk_AllJets_NI/SKIM_Tau_31OttD_05Oct2015               -i inputFiles/miniAODv2VSfitForTalk/1_Tau__Run2015D-05Oct2015-v1.txt
# python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 30 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims17_AllJets_NI/SKIM_SingleElectron_31OttD_05Oct2015    -i inputFiles/DataRunDTrigFix4Nov/3_SingleElectron__Run2015D-05Oct2015-v1.txt

# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsDY_Stitch2/SKIM_DY_Inclusive   -i inputFiles/DY_LO/DY_Inclusive.txt   -x 6025.2 -y 0.961214096 -z 100
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsDY_Stitch2/SKIM_DY_100_200     -i inputFiles/DY_LO/DY_100_200.txt           -x 6025.2 -y 0.028478039
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsDY_Stitch2/SKIM_DY_200_400     -i inputFiles/DY_LO/DY_200_400.txt           -x 6025.2 -y 0.008733401
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsDY_Stitch2/SKIM_DY_400_600     -i inputFiles/DY_LO/DY_400_600.txt           -x 6025.2 -y 0.001122983
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsDY_Stitch2/SKIM_DY_600_Inf     -i inputFiles/DY_LO/DY_600_Inf.txt           -x 6025.2 -y 0.000451481
# 
# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsDY_Stitch2/SKIM_DY_LO_LeftAsInclusive -i inputFiles/DY_LO/DY_Inclusive.txt   -x 6025.2

# python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/SkimsDY_Stitch2/SKIM_DY_NLO -i inputFiles/DY_LO/DY_NLO.txt   -x 6025.2



### DATA - Silver JSOn - 5 Gennaio 2016
python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 40 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_SingleMuon_RunD        -i inputFiles/miniAODv2_silverJSON_5Gen2016/SingleMuon_RunD_merged.txt
python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 40 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_Tau_RunD               -i inputFiles/miniAODv2_silverJSON_5Gen2016/Tau_RunD_merged.txt
python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 40 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_SingleElectron_RunD    -i inputFiles/miniAODv2_silverJSON_5Gen2016/SingleElectron_RunD_merged.txt

python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_SingleMuon_RunC        -i inputFiles/miniAODv2_silverJSON_5Gen2016/8_SingleMuon__Run2015C_25ns-05Oct2015-v1.txt
python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_Tau_RunC               -i inputFiles/miniAODv2_silverJSON_5Gen2016/7_Tau__Run2015C_25ns-05Oct2015-v1.txt
python scripts/skimNtuple.py -d True  -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_SingleElectron_RunC    -i inputFiles/miniAODv2_silverJSON_5Gen2016/9_SingleElectron__Run2015C_25ns-05Oct2015-v1.txt


### MC samples - Silver JSON (noHFMET) - 5 Gennaio 2016
# DY - stitch
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_DY_Inclusive   -i inputFiles/miniAODv2_silverJSON_5Gen2016/8_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt               -x 6025.2 -y 0.961214096 -z 100
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_DY_100_200     -i inputFiles/miniAODv2_silverJSON_5Gen2016/9_DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 6025.2 -y 0.028478039
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_DY_200_400     -i inputFiles/miniAODv2_silverJSON_5Gen2016/10_DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt  -x 6025.2 -y 0.008733401
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_DY_400_600     -i inputFiles/miniAODv2_silverJSON_5Gen2016/11_DYJetsToLL_M-50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt  -x 6025.2 -y 0.001122983
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_DY_600_Inf     -i inputFiles/miniAODv2_silverJSON_5Gen2016/12_DYJetsToLL_M-50_HT-600toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt  -x 6025.2 -y 0.00045148

# WJets - stitch
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 50 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WJets_Inclusive   -i inputFiles/miniAODv2_silverJSON_5Gen2016/3_WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt              -x 61526.7 -y 0.965405 -z 100
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WJets_100_200     -i inputFiles/miniAODv2_silverJSON_5Gen2016/4_WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt  -x 61526.7 -y 0.0265338
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WJets_200_400     -i inputFiles/miniAODv2_silverJSON_5Gen2016/5_WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt  -x 61526.7 -y 0.00709607
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WJets_400_600     -i inputFiles/miniAODv2_silverJSON_5Gen2016/6_WJetsToLNu_HT-400To600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt  -x 61526.7 -y 0.000964885
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WJets_600_Inf     -i inputFiles/miniAODv2_silverJSON_5Gen2016/7_WJetsToLNu_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt  -x 61526.7 -y 0.00037029

# Others - non stitched
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 130 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_TT_merged     -i inputFiles/miniAODv2_silverJSON_5Gen2016/TT_merged.txt   -x 769.00

# HH signal new xsec 13TeV and analytical values of the ratios 
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_HHLambda1         -i inputFiles/miniAODv2_silverJSON_5Gen2016/HH_Lambda1.txt        -x 0.002729241983
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_HHLambda20        -i inputFiles/miniAODv2_silverJSON_5Gen2016/HH_Lambda20.txt       -x 0.245931995088
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_HHLambdam4        -i inputFiles/miniAODv2_silverJSON_5Gen2016/HH_Lambdam4.txt       -x 0.03370613849  
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_HHLambda2dot46    -i inputFiles/miniAODv2_silverJSON_5Gen2016/HH_Lambda2dot46.txt   -x 0.00114891262213  

python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_ST_tW_antitop_5f_inclusiveDecays   -i inputFiles/miniAODv2_silverJSON_5Gen2016/31_ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 35.6
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 20 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_ST_tW_top_5f_inclusiveDecays       -i inputFiles/miniAODv2_silverJSON_5Gen2016/32_ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt       -x 35.6

python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-250   -i inputFiles/miniAODv2_silverJSON_5Gen2016/14_GluGluToRadionToHHTo2B2Tau_M-250_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-260   -i inputFiles/miniAODv2_silverJSON_5Gen2016/15_GluGluToRadionToHHTo2B2Tau_M-260_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-270   -i inputFiles/miniAODv2_silverJSON_5Gen2016/16_GluGluToRadionToHHTo2B2Tau_M-270_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-280   -i inputFiles/miniAODv2_silverJSON_5Gen2016/17_GluGluToRadionToHHTo2B2Tau_M-280_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-300   -i inputFiles/miniAODv2_silverJSON_5Gen2016/18_GluGluToRadionToHHTo2B2Tau_M-300_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-320   -i inputFiles/miniAODv2_silverJSON_5Gen2016/19_GluGluToRadionToHHTo2B2Tau_M-320_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-340   -i inputFiles/miniAODv2_silverJSON_5Gen2016/20_GluGluToRadionToHHTo2B2Tau_M-340_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-350   -i inputFiles/miniAODv2_silverJSON_5Gen2016/21_GluGluToRadionToHHTo2B2Tau_M-350_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-400   -i inputFiles/miniAODv2_silverJSON_5Gen2016/22_GluGluToRadionToHHTo2B2Tau_M-400_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-450   -i inputFiles/miniAODv2_silverJSON_5Gen2016/23_GluGluToRadionToHHTo2B2Tau_M-450_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt   -x 10.0
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_GluGluToRadionToHHTo2B2Tau_M-500   -i inputFiles/miniAODv2_silverJSON_5Gen2016/24_GluGluToRadionToHHTo2B2Tau_M-500_narrow_13TeV-madgraph__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt   -x 10.0

python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WWToLNuQQ      -i inputFiles/miniAODv2_silverJSON_5Gen2016/36_WWToLNuQQ_13TeV-powheg__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt -x 49.997
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WWTo2L2Nu      -i inputFiles/miniAODv2_silverJSON_5Gen2016/37_WWTo2L2Nu_13TeV-powheg__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt -x 12.178
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WZTo2L2Q       -i inputFiles/miniAODv2_silverJSON_5Gen2016/38_WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt -x 5.595
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WZTo3LNu       -i inputFiles/miniAODv2_silverJSON_5Gen2016/39_WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt -x 4.42965
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WZTo1L3Nu      -i inputFiles/miniAODv2_silverJSON_5Gen2016/40_WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt -x 3.05
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_WZTo1L1Nu2Q    -i inputFiles/miniAODv2_silverJSON_5Gen2016/41_WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt -x 10.71
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_ZZTo2L2Nu      -i inputFiles/miniAODv2_silverJSON_5Gen2016/33_ZZTo2L2Nu_13TeV_powheg_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2.txt -x 0.564
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_ZZTo2L2Q       -i inputFiles/miniAODv2_silverJSON_5Gen2016/34_ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt -x 3.22
python scripts/skimNtuple.py -s True -c  config/skim.cfg  -n 10 -k True -o /data_CMS/cms/cadamuro/test_submit_to_tier3/Skims31_AllJets_NI/SKIM_ZZTo4L         -i inputFiles/miniAODv2_silverJSON_5Gen2016/35_ZZTo4L_13TeV-amcatnloFXFX-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1.txt -x 1.212

